wedding_server/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resource :home, :only => [:show, :index]
  
  resources :rsvps, :only => [:create, :index]

  root to: "home#index"
end

wedding_server/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

wedding_server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

wedding_server/app/models/food_option.rb
class FoodOption < ApplicationRecord
	has_many :rsvps
end

wedding_server/app/models/rsvp.rb
class Rsvp < ApplicationRecord
	belongs_to :food_option
end

wedding_server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

wedding_server/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

wedding_server/app/controllers/rsvp_controller.rb
class RsvpController < ApplicationController
    def create
      Rsvp.create(person_params)
    end

    def person_params
      params.require(:rsvp).permit(
        :attending,
        :dietary_note,
        :first_name,
        :food_option_id,
        :last_name
      )
    end
end

wedding_server/app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
    layout "rsvp"

    before_action :authenticate_admin!, :only => [:index]

    def index
      @rsvps = Rsvp.all()
      @signed_in = admin_signed_in?
    end

    def create
      Rsvp.create(person_params)
    end

    def person_params
      params.require(:rsvp).permit(
        :attending,
        :dietary_note,
        :first_name,
        :food_option_id,
        :last_name
      )
    end
end

wedding_server/app/helpers/application_helper.rb
module ApplicationHelper
end

wedding_server/app/views/home/index.html.erb
<%= javascript_pack_tag 'application' %>
<h1>Lizzie & Carlos are (finally) getting married!</h1>
<div>
	<dl>
		<dt>Where?</dt>
		<dd>- At the Glasbern Inn in Fogelsville, PA</dd>
		<dt>When?</dt>
		<dd>- At 4pm on Friday, October 26th, 2018</dd>
		<dt>Why?</dt>
		<dd>- Tax breaks, Lizzie gets to wear more jewelry, Lizzie gets to wear a pretty dress, parents seem to like this sort of thing, LUB LUB LUB, etc</dd>
	</dl>

  <div>Hey there! Thanks for visiting our website! RSVP functionality is coming soon, along with lots more information about the big day and some other fun tidbits.</div>
  <div>In the meantime, if you're looking to book the hotel room, here's the info:</div>
  <div>Wingate by Wyndham Allentown</div>
  <div>4325 Hamilton Blvd.</div>
  <div>Allentown, PA 18103</div>
  <div>610-366-1600</div>

  <div>Call and ask for a room under the 'Wolensky-Gadea Wedding'</div>

  <div>We can't wait celebrate with you!</div>
</div>

wedding_server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeddingServer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

wedding_server/app/views/layouts/rsvp.html.erb
<%= stylesheet_link_tag "rsvp" %>
<%= yield %>

wedding_server/app/views/rsvps/index.html.erb
<table>
  <tbody>
    <% @rsvps.each do |rsvp|%>
      <tr>
        <td><%= rsvp.first_name %></td>
        <td><%= rsvp.last_name %></td>
        <td><%= rsvp.attending %></td>
        <td><%= rsvp.food_option.name %></td>
        <td><%= rsvp.dietary_note %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @signed_in %>
  <%= button_to('Logout', destroy_admin_session_path, :method => :delete) %>
<% end %>